# Generated by Django 4.1.1 on 2022-09-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_discussion_forum_alter_discussion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(allow_unicode=True, choices=[('noslug', 'Noslug'), ('haveslug', 'Haveslug')], default='Haveslug', max_length=250, null=True, unique=True, unique_for_date='publish'),
        ),
    ]
