# Generated by Django 4.1.1 on 2022-09-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_discussion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(allow_unicode=True, choices=[('draft', 'Draft'), ('published', 'Published'), ('noslug', 'Noslug'), ('haveslug', 'Haveslug')], default='haveslug', max_length=250, null=True, unique=True, unique_for_date='publish'),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('noslug', 'Noslug'), ('haveslug', 'Haveslug')], default='draft', max_length=10),
        ),
    ]
