# Generated by Django 4.1.1 on 2022-09-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_discussion_slug_alter_discussion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(allow_unicode=True, choices=[('draft', 'Draft'), ('published', 'Published'), ('noslug', 'Noslug'), ('haveslug', 'Haveslug')], default='haveslug', null=True, unique=True, unique_for_date='publish'),
        ),
    ]
