# Generated by Django 4.1.1 on 2022-09-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_discussion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
