# Generated by Django 4.1.1 on 2022-09-18 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_alter_discussion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', related_query_name='published', to='forum.discussion'),
        ),
    ]
