# Generated by Django 4.1.1 on 2022-09-21 17:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_alter_discussion_discuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
