# Generated by Django 4.1.1 on 2022-09-21 18:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_discussion_discuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=tinymce.models.HTMLField(),
        ),
    ]
