# Generated by Django 4.1.1 on 2022-09-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_alter_discussion_discuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
