# Generated by Django 4.1.1 on 2022-10-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_discussion_claps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='claps',
            field=models.BigIntegerField(default=0),
        ),
    ]
