# Generated by Django 4.1.1 on 2022-10-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0020_alter_discussion_claps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', related_query_name='published', to='forum.discussion'),
        ),
    ]
