"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from django.contrib import messages

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2-6@(k_m&!5i&ov(zdt)7do&@i^_%8s-9ms*c&+4)aa_gtt2ff'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'forum',
    'users',
    'tinymce',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'forum',
        'USER': 'profmorten',
        'PASSWORD': 'Wtrekker76',
        'HOST': 'localhost',
        'PORT': '',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
if DEBUG:

    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'staticfiles'

    STATICFILES_DIRS = [
	BASE_DIR / "static",
    ]
# media folder settings
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

else:
    STATIC_URL = '/static/'
    STATIC_ROOT = BASE_DIR / 'static'

    # media folder settings
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'


MESSAGE_TAGS = {
	messages.ERROR: 'danger',
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
## Enable Custom user model extending AbstractBaserUser
AUTH_USER_MODEL = 'users.NewUser'



TINYMCE_DEFAULT_CONFIG = {
	'cleanup_on_startup': False,
	'custom_undo_redo_levels': 20,
	'selector': '.tinymce',
	'media_dimensions': False,
	'height': '350',
	'theme': 'silver',
	'force_br_newlines': True,
	'force_p_newlines': False,
	'autosave_ask_before_unload': True,
	'autosave_restore_when_empty': True,
	'forced_root_block': '',
	'convert_urls': False,
	'autosave_interval': '20s',
	'image_dimensions': False,
	'object_resizing': False,
	'browser_spellcheck': True,
	'mobile': {
		'menubar': True
	},
	'fontsize_formats': "12pt 14pt",

	'plugins': '''
            textcolor save link image media preview codesample contextmenu
            table code lists fullscreen  insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code fullscreen autolink lists  charmap print  hr
            anchor pagebreak
            ''',
	'toolbar1': '''
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect  | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media | codesample |
            ''',
	'contextmenu': 'formats | link image',
	'menubar': True,
	'statusbar': True,
	'image_class_list': [
		{'title': 'Responsive', 'value': 'img-fluid'},
	],

	'extended_valid_elements': [
		"ul[class=list-group list-group-numbered list-group-flush]",
		"li[class=list-group-item d-flex justify-content-between align-items-start flex-fill fancy-border-list pt-2]"
]

}
